server:
  port: 8090
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mkushekov/microservices-spring-cloud.git
          search-paths: configuration
          default-label: main
